spring:
  application:
    name: todo

  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true

server:
  error:
    include-message: always

logging:
  level:
    org.hibernate.SQL: debug
